type = "checkout_ui_extension"
name = "upsell-app"

extension_points = [
  'Checkout::CartLines::RenderAfter'
]

[capabilities]
  network_access = true
  api_access = true

[[settings.fields]]
  key = "trigger_products"
  type = "multi_line_text_field"
  name = "Trigger product variant ids"

[[settings.fields]]
  key = "variant"
  type = "variant_reference"
  name = "Upsell product"

[[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner."