type = "checkout_ui_extension"
name = "upsell-app"

extension_points = [
  'Checkout::CartLines::RenderAfter'
]

[capabilities]
  network_access = true
  api_access = true



[[settings.fields]]
  key = "variant"
  type = "variant_reference"
  name = "Upsell product"

[[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner."

[[settings.fields]]
  key = "description"
  type = "single_line_text_field"
  name = "Banner description"
  description = "Enter a description for the banner."

[[settings.fields]]
  key = "status"
  type = "single_line_text_field"
  name = "Banner status"
  [[settings.fields.validations]]
    name = "choices"
    value = "[\"info\", \"success\", \"warning\", \"critical\"]"

[[settings.fields]]
  key = "collapsible"
  type = "boolean"
  name = "Show collapsible description."
  description = "Display controls to expand or collapse the banner description."
