type = "checkout_ui_extension"
name = "upsell-app"

extension_points = [
  'Checkout::CartLines::RenderAfter'
]

[capabilities]
  network_access = true
  api_access = true

# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"
